### ISSUE TITLE
DESCRIPTIVE LINKED LIST

### ISSUE THREAD

**Issue by rnabeel** [smfai200/Data-Structure-Assignments#1]
Upload a simple file for simple Link list in python/java with as much description as possible in it :/

**Comment by smfai200** [comment]
Surely, You need intermediate programming knowledge. Data Structure comes in at advanced Level, so you really need to learn about the concepts of References, cloning of Pointers in java(Class References are Used in JAVA for such). Although, if you want to go easy, there is a build-in Library for Linked-List which has all the methods implemented by default.

LinkedList<String> a=new LinkedList<String>();  
a.add("NABEEL");

**Comment by smfai200** [comment]
https://github.com/smfai200/Data-Structure-Assignments/blob/master/4.%20LinkedList%20(Single-Basic)/LinkedList.java

Refer for the Most Basic LinkedList!
